branch-defaults:
  aws:
    environment: ItemCatalog-env
    group_suffix: null
  aws-eb:
    environment: ItemCatalog-env
  master:
    environment: ItemCatalog-env
environment-defaults:
  ItemCatalog-env:
    branch: null
    repository: null
global:
  application_name: item-catalog
  branch: null
  default_ec2_keyname: null
  default_platform: Python 3.6
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
